env:
  es2021: true
  browser: false
  node: true
extends:
  - eslint-config-love
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - prettier
overrides: []
parserOptions:
  project: ["./tsconfig.json"]
  ecmaVersion: latest
  sourceType: module
rules:
  "@typescript-eslint/consistent-type-definitions": off
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-non-null-assertion": off
